# Global confiuration: Applied to all files

# printWidth = 80
# tabWidth = 4
# useTabs = true
semi = false
singleQuote = false
quoteProps = "as-needed"
jsxSingleQuote = false
trailingComma = "es5"
bracketSpacing = true
objectWrap = "preserve"
bracketSameLine = false
arrowParens = "always"
# rangeStart = 0
# rangeEnd = "Infinity"
requirePragma = true
insertPragma = true
checkIgnorePragma = true
proseWrap = "always"
htmlWhitespaceSensitivity = "css"
vueIndentScriptAndStyle = true
# endOfLine = "lf"
embeddedLanguageFormatting = "auto"
singleAttributePerLine = false

# Overrides used to specify format for specific files

[[overrides]]
files = "*.md"

[overrides.options]
printWidth = 80
tabWidth = 2
